### ISSUE TITLE
Any way to disable update emails?

### ISSUE THREAD

**Issue by JohnKiller** [Jamesits/pve-fake-subscription#1]
Thanks for this script.

I'm using it in my lab, with test repository enable, and my email is spammed with updates. Official proxmox won't fix this because the production repo gets updated less frequently.

Do you think there is a way to fix it in some way?

Thanks

**Comment by Jamesits** [comment]
I don't see it configurable from GUI; [a patch is available](https://bugzilla.proxmox.com/show_bug.cgi?id=1295) though.

**Comment by Jamesits** [comment]
Closing due to not my fault; if you have further requests please comment below.

**Comment by JohnKiller** [comment]
Hi, the feature is now merged onto Proxmox. For anyone coming here, you can disable emails by going to Datacenter -> Options -> Notify -> Package Updates and set to Never
