### ISSUE TITLE
Publish package as APT repo

### ISSUE THREAD

**Issue by JohnKiller** [Jamesits/pve-fake-subscription#12]
Hi, just wondering if it's a feature you would consider.

There are GitHub actions that will create an APT repository as a GitHub Pages repo.

I can help with a pull request if interested.

**Comment by Jamesits** [comment]
If you want to install this program onto a single PVE host, the experience is already kinda set-and-forget. While I agree that a streamlined user experience (a deb repo, automated upgrades, etc.) and *professionalism* wording (as in #11) would make it easier for people to use this program, these changes are going to benefit those who want to deploy this in batch or in a commercial setting a lot more than those who have 1-2 servers in their own homelab. 

Please remember the Proxmox series of software, though fully open source, is maintained and supported by one company, and that company runs on the subscription model. Those who deploy Proxmox software in batch are their target customers. If these customers don't pay the developers, we don't get free software too. 

So from the beginning of this project, I've decided to discourage the use of this program in a commercial setting leveraging the invisible hand:
- a "license" with NSFW wording
- references to a gay meme
- providing the bare minimum of the instructions
- no automation by default
- etc. 

These methods create a controlled insecurity feeling. The whole idea is that if a company want to use Proxmox software, but can't even modify this simple script to make it "appropriate", they should really consider purchasing a support plan. 

That said, this program is still free (as in free whatever). If you want to modify it, go ahead. If you want to distribute it in another way, I wouldn't (and can't) stop you. People have forked it and put adverts of their MSP company in it; I don't like this but I don't have control over this either. And you can always argue with me or try to convince me. I'm always open to new ideas.

**Comment by JohnKiller** [comment]
Understandable, have a nice day.

**Comment by Games-Crack** [comment]
While i understand that i just dont like explaining that every time someone sees it.
Anyways i forked it if you want you can open a PR there.

**Comment by chattytak** [comment]
Hello.
I am a home lab user. Therefore, I appreciate this repository.
And I agree with the idea that if it is for business use, you should buy a paid subscription.

However, I did not understand the logic behind the appearance of "YajuuSenpai" as a reason for hesitation.
For example, I think "cracked" or "beggar" or "thug" would be much more hesitant.
Well, this suggestion is half a joke.

**Comment by Jamesits** [comment]
@chattytak
> However, I did not understand the logic behind the appearance of "YajuuSenpai" as a reason for hesitation. 

I don't like the idea of cracked/begger since it feels like I'm standing on the moral high ground and peeing onto the head of those poor users. So I simply reference NSFW jokes everywhere (because they are NSFW, you are not going to use it for work, right?) :)

**Comment by chattytak** [comment]
Regardless of what string is displayed, this repository is working correctly. Therefore, I think anything more is a matter of faith.

If poverty is really the reason, then using Linux KVM, which is the base technology of Proxmox, would not cause any problems.
Nevertheless, I feel that daring to choose Proxmox and then using this repository is cracking and begging. Therefore, I have nothing to complain about being called a beggar by using this repository, and I consider myself obliged to admit it.
However, according to your logic, the string "YajuuSenpai" was an exoneration, bailing me out of feeling guilty. I appreciate your thoughtfulness ;)

**Comment by littlecxm** [comment]
> However, I did not understand the logic behind the appearance of "YajuuSenpai" as a reason for hesitation.

「良い世、来いよ」😁
