### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by MiRen76** [Jamesits/pve-fake-subscription#13]
I downloaded the file "pve-fake-subscription_0.0.9+git-1_all.deb" and ran it as root on my pbs.
After that  I received tho following error:

dpkg-deb: error: 'pve-fake-subscription_0.0.9_all.deb' is not a Debian format archive
dpkg: error processing archive pve-fake-subscription_0.0.9_all.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 pve-fake-subscription_0.0.9_all.deb

**Comment by Jamesits** [comment]
Please confirm you are downloading the actual archive rather than the GitHub redirect page... Try downloading with a browser then upload the file with SSH if in doubt.

**Comment by hvisage** [comment]
@MiRen76  also remember to check the checksums against the sha256sum.txt
as found at https://github.com/Jamesits/pve-fake-subscription/releases/tag/v0.0.9

**Comment by Jamesits** [comment]
Closing due to no reply for a long time. If the issue persists, please feel free to comment below.
