### ISSUE TITLE
Any idea to solve No Proxmox VE repository is enabled warning?

### ISSUE THREAD

**Issue by mylovesaber** [Jamesits/pve-fake-subscription#2]
The tool is great, but there is still one small flaw, I don't know how difficult it is for you to implement:
Condition:
1. If you have not made any changes to the source mirror after installing the system, in Datacenter - pve - Updates - Repositories, you can see a nearly perfect interface showing camouflage
2. Since the subscription is not really obtained, if the /etc/apt/sources.list.d/pve-enterprise.list file is not deleted, apt update will stop at the stage of updating enterprise.proxmox.com, I searched online. However, it seems that it is impossible to specify a source mirror not to update?
3. If I delete the /etc/apt/sources.list.d/pve-enterprise.list file or rename it to pve-enterprise.list.bak, and refresh the pve web page, the green interface camouflage will restore the red X and hint:
No Proxmox VE repository is enabled, you do not get any updates!

So is there a way to still display subscribed disguises without the /etc/apt/sources.list.d/pve-enterprise.list file?

**Comment by Jamesits** [comment]
I think it is technically possible to cheat against that web UI check. But the whole point of this project is to disable the "no subscription" dialog and save one mouse click. Working around more logic to disguise the system as a fully licensed one is out of the scope of this project, and I don't have any personal motivation on implementing it. 

If you really want to implement it yourself, there are 2 possible ways I can think of:
- proxy the enterprise.proxmox.com domain and redirect it to a valid repository
- patch the detection logic
Both methods are very simple and can be done in less than 1 hour.
