### ISSUE TITLE
Strange unit file in Package

### ISSUE THREAD

**Issue by thojo0** [Jamesits/pve-fake-subscription#3]
There is a strange unit file in the deb package.
It's located hear: lib/systemd/system/pve-fake-subscription.timer.service

I don't think its necessary so maybe remove it from the package in the next version.

**Comment by Jamesits** [comment]
Thanks for the heads up. It's due to a workaround on one of fpm's issue. To remove this we might need to ditch fpm completely for now. 
ref: https://github.com/jordansissel/fpm/pull/1460

**Comment by Jamesits** [comment]
FPM -> nFPM migration is completed.
