### ISSUE TITLE
Error after 7.2-11 update

### ISSUE THREAD

**Issue by Pharrcyde** [Jamesits/pve-fake-subscription#4]
I got the following error window after updating to 7.2-11 today.
`invalid type: integer `1663255405`, expected a string at line 1 column 178 (500)`
It shows up when I go to Support in Datacenter.
Also under node, it shows up in Summary, clickling "Refresh" in Updates, and when clicking on Repositories as well.
I still get the error without the dark theme installed.
![image](https://user-images.githubusercontent.com/5461458/190447607-f45fca14-4208-430f-89ce-6e05ed585130.png)

The issue goes away after purging [pve-fake-subscription_0.0.7_all.deb](https://github.com/Jamesits/pve-fake-subscription/releases/download/v0.0.7/pve-fake-subscription_0.0.7_all.deb)

**Comment by Luxxy-GF** [comment]
same issue here went away after purging

**Comment by voodoopt** [comment]
Same problem :(

**Comment by Jamesits** [comment]
Please update to [v0.0.8](https://github.com/Jamesits/pve-fake-subscription/releases/tag/v0.0.8).

**Comment by denimalau** [comment]
> Please update to [v0.0.8](https://github.com/Jamesits/pve-fake-subscription/releases/tag/v0.0.8).

Damn that was fast. Thank you so much 😎

**Comment by voodoopt** [comment]
Thank you ;)
