### ISSUE TITLE
Non-Functional in 7.2-14 and later

### ISSUE THREAD

**Issue by molten360** [Jamesits/pve-fake-subscription#7]
Upgraded my clusters to 7.2-14. Found that it causes the GUI to not function. The Gui, upon login receives an error "invalid type: integer `1669327931`, expected a string at line 1 column 178 (500)". All Noes show a question mark and no migrations or backup tasks that are cluster wide function.

It appears that quorum is fine when running pvecm status

One uninstalled using the "apt purge pve-fake-subscription" the nodes immediately come online and show a green check mark, and all GUI functions start working as intended.

**Comment by Jamesits** [comment]
Try [the latest release](https://github.com/Jamesits/pve-fake-subscription/releases/latest).

**Comment by Jamesits** [comment]
Closing due to lack of response. If the problem continues to happen after you upgrade to the latest version, feel free to create a new issue.
